# Generated by Django 5.0.4 on 2024-12-26 06:41

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProfileDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Employee Code"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Full Name")),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Other", "Other"),
                        ],
                        max_length=10,
                        verbose_name="Gender",
                    ),
                ),
                (
                    "mobile",
                    models.CharField(max_length=15, verbose_name="Mobile Number"),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email Address"
                    ),
                ),
                (
                    "father_name",
                    models.CharField(max_length=100, verbose_name="Father's Name"),
                ),
                (
                    "spouse_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Spouse's Name",
                    ),
                ),
                ("present_address", models.TextField(verbose_name="Present Address")),
                (
                    "permanent_address",
                    models.TextField(verbose_name="Permanent Address"),
                ),
                ("dob", models.DateField(verbose_name="Date of Birth")),
                (
                    "blood_group",
                    models.CharField(
                        blank=True, max_length=5, null=True, verbose_name="Blood Group"
                    ),
                ),
                (
                    "emergency_contact",
                    models.CharField(
                        max_length=15, verbose_name="Emergency Contact Number"
                    ),
                ),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="profile_images/",
                        verbose_name="Profile Image",
                    ),
                ),
            ],
        ),
    ]
